import { DataTypes } from "sequelize";
import { sequelize } from "../db/conexion.js";

import {  MarcaModel } from "./MarcaModel.js";

export const ModeloModel = sequelize.define(
  "modelos",
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    descripcion: {
        type: DataTypes.STRING,
        allowNull: false,
        },
      state: {
        type: DataTypes.BOOLEAN,
        defaultValue: true,
      }
  },
  {
    timestamps: false,
  }  
  );MarcaModel.hasMany(ModeloModel, { foreignKey: "id_marca" });
  ModeloModel.belongsTo(MarcaModel, { foreignKey: "id_marca" });
  const marcasData = [
    {
      descripcion: "Toyota",
      modelos: [
        { descripcion: "OROLLA" },
        { descripcion: "YARIS" },
        { descripcion: "AVENIS" },
        { descripcion: "CAMRY" },
        { descripcion: "AURIS" },
        { descripcion: "4 RUNNER " },
        { descripcion: "ALLEX" },
        { descripcion: "ALLION" },
        { descripcion: "ALTEZZA" },
        { descripcion: "AQUA" },
        { descripcion: "ARISTO" },
        { descripcion: "AURION" },
        { descripcion: "AURIS HYBRID" },
        { descripcion: "AURIS HYBRIDE" },
        { descripcion: "AVALON" },
        { descripcion: "AVENSIS VERSO" },
        { descripcion: "AYGO" },
        { descripcion: "BANDIRANTE" },
        { descripcion: "BB" },
        { descripcion: "BELTA" },
        { descripcion: "BLADE" },
        { descripcion: "BREVIS" },
        { descripcion: "BZ4Z" },
        { descripcion: "C-HR" },
        { descripcion: "CALDINA" },
        { descripcion: "CAMI " },
        { descripcion: "CAMRY GRACIA" },
        { descripcion: "CAMRY SOLARA" },
        { descripcion: "CARIB" },
        { descripcion: "CARINA" },
        { descripcion: "CARINA ED" },
        { descripcion: "CAVALIER" },
        { descripcion: "CELICA" },
        { descripcion: "CELISOR" },
        { descripcion: "CENTURY" },
        { descripcion: "CHASER" },
        { descripcion: "CHR" },
        { descripcion: "COROLLA FIELDER" },
        { descripcion: "COROLLA LEVIN" },
        { descripcion: "COROLLA SPACIO" },
        { descripcion: "CORONA " },
        { descripcion: "CORONA EXIV" },
        { descripcion: "CORONA PREMIO" },
        { descripcion: "CORSA" },
        { descripcion: "CRESSIDA" },
        { descripcion: "CRESTA" },
        { descripcion: "CROWN" },
        { descripcion: "CROWN ATHLETE" },
        { descripcion: "CROWN MAJESTA" },
        { descripcion: "CURREN" },
        { descripcion: "CYNOS" },
        { descripcion: "DUET" },
        { descripcion: "E" },
        { descripcion: "ECHO" },
        { descripcion: "ETIOS" },
        { descripcion: "J CRUISER" },
        { descripcion: "FORTUNER" },
        { descripcion: "FUNCARGO" },
        { descripcion: "GAIA" },
        { descripcion: "GLANZA" },
        { descripcion: "GR86" },
        { descripcion: "GT86" },
        { descripcion: "HARRIER" },
        { descripcion: "HDI 100" },
        { descripcion: "HIGHLANDER" },
        { descripcion: "HILUX" },
        { descripcion: "HYRYDER" },
        { descripcion: "INNOVA" },
        { descripcion: "IPSUM" },
        { descripcion: "IQ" },
        { descripcion: "ISIS" },
        { descripcion: "IST" },
        { descripcion: "KLUGER" },
        { descripcion: "LAND CRUISER" },
        { descripcion: "LAND CRUISER 200" },
        { descripcion: "LAND CRUISER PRADO" },
        { descripcion: "LIVA" },
        { descripcion: "MARK ||" },
        { descripcion: "MARK X" },
        { descripcion: "MARK X ZIO" },
        { descripcion: "MATRIZ" },
        { descripcion: "MIRAI" },
        { descripcion: "MR" },
        { descripcion: "MR2" },
        { descripcion: "MRS" },
        { descripcion: "NADIA" },
        { descripcion: "OPA" },
        { descripcion: "RIGIN" },
        { descripcion: "PASEO" },
        { descripcion: "PASSO" },
        { descripcion: "PICNIC" },
        { descripcion: "PLATZ " },
        { descripcion: "PREMIO" },
        { descripcion: "PRIME" },
        { descripcion: "PRIUS" },
        { descripcion: "PRIUS +" },
        { descripcion: "PROBOX" },
        { descripcion: "PROGRES" },
        { descripcion: "PRONARD" },
        { descripcion: "QUALIS" },
        { descripcion: "REACTIS" },
        { descripcion: "RAIZE" },
        { descripcion: "RAUM" },
        { descripcion: "RAV 4" },
        { descripcion: "ROOMY" },
        { descripcion: "RUSH" },
        { descripcion: "SAI" },
        { descripcion: "SCEPTER" },
        { descripcion: "SCION" },
        { descripcion: "SEQUAOIA" },
        { descripcion: "SERA" },
        { descripcion: "SIENTA" },
        { descripcion: "SOARER" },
        { descripcion: "SOLARA " },
        { descripcion: "TUNDRA" },
        { descripcion: "URBAN" },
        { descripcion: "VANGUARD" },
        { descripcion: "VENTURY" },
        { descripcion: "VENZA" },
        { descripcion: "YARIS" },

      ],
    },
    {
      descripcion: "Chevrolet",
      modelos: [
        { descripcion: "AVEO" },
        { descripcion: "CRUZE" },
        { descripcion: "LICETTI" },
        { descripcion: "LANOS" },
        { descripcion: "SPARK" },
        { descripcion: "AGILE" },
        { descripcion: "ASTRA" },
        { descripcion: "AVALANCHE" },
        { descripcion: "BEAT" },
        { descripcion: "BLAZER" },
        { descripcion: "BOLT" },
        { descripcion: "CAMARO" },
        { descripcion: "CAPRICE" },
        { descripcion: "CAPTIVA" },
        { descripcion: "CARAVAN" },
        { descripcion: "CAVALIER" },
        { descripcion: "CELTA" },
        { descripcion: "CHEVETTE" },
        { descripcion: "CHEVI C2" },
        { descripcion: "CLASSIC" },
        { descripcion: "COBALT" },
        { descripcion: "COLORADO" },
        { descripcion: "CORSA" },
        { descripcion: "CORSICA" },
        { descripcion: "CORVETE" },
        { descripcion: "D20 VERANEIO" },
        { descripcion: "ENJOY" },
        { descripcion: "EPICA" },
        { descripcion: "EQUINOX" },
        { descripcion: "EVANDA" },
        { descripcion: "GEO STORM" },
        { descripcion: "GEO TRACKER" },
        { descripcion: "HAVRE" },
        { descripcion: "IMPALA" },
        { descripcion: "IPANEMA" },
        { descripcion: "K3500" },
        { descripcion: "KADETT" },
        { descripcion: "KALOS" },
        { descripcion: "LUMINA" },
        { descripcion: "MALIBU" },
        { descripcion: "MATIZ" },
        { descripcion: "MERIVA" },
        { descripcion: "METRO" },
        { descripcion: "MONTANA" },
        { descripcion: "MONTE CARLO" },
        { descripcion: "MONZA" },
        { descripcion: "MW" },
        { descripcion: "NEXIA" },
        { descripcion: "NIVA" },
        { descripcion: "NOVA" },
        { descripcion: "NUBIRA" },
        { descripcion: "OMEGA" },
        { descripcion: "ONIX LS" },
        { descripcion: "ONIX PLUS" },
        { descripcion: "OPALA" },
        { descripcion: "ORLANDO" },
        { descripcion: "PRISMA" },
        { descripcion: "REZZO" },
        { descripcion: "S-10" },
        { descripcion: "SAL SEDAN" },
        { descripcion: "SAIL U-VA" },
        { descripcion: "SILVER" },
        { descripcion: "SILVERADO" },
        { descripcion: "SONIC" },
        { descripcion: "SPIN" },
        { descripcion: "SSR" },
        { descripcion: "SUBURBAN" },
        { descripcion: "TACUMA" },
        { descripcion: "THAOE" },
        { descripcion: "TAVERA" },
        { descripcion: "TIGRA" },
        { descripcion: "TORNADO" },
        { descripcion: "TRACKER" },
        { descripcion: "TRAILBLAZER" },
        { descripcion: "TRANS SPORT" },
        { descripcion: "TRAVERSE" },
        { descripcion: "TRAX" },
        { descripcion: "UPLANDER" },
        { descripcion: "VECTRA" },
        { descripcion: "VENTURE" },
        { descripcion: "VIVA" },
        { descripcion: "VOLT" },
        { descripcion: "ÓNIX" },
      ],
    },
    {
      descripcion: "HIUNDAI",
      modelos: [
        { descripcion: "SOALRIS" },
        { descripcion: "ACCENT" },
        { descripcion: "I30" },
        { descripcion: "I20" },
        { descripcion: "GETZ" },
        { descripcion: "4S FLUIDIC VERNA" },
        { descripcion: "ALCAZAR" },
        { descripcion: "ATOS" },
        { descripcion: "ATOS PRIME" },
        { descripcion: "AURA" },
        { descripcion: "AVANTE" },
        { descripcion: "AZERA" },
        { descripcion: "BAYON" },
        { descripcion: "CENTENNIAL" },
        { descripcion: "COUPE" },
        { descripcion: "CRETA" },
        { descripcion: "DINASTY" },
        { descripcion: "ELANTRA" },
        { descripcion: "ELITE I20" },
        { descripcion: "EON" },
        { descripcion: "EQUUS" },
        { descripcion: "EXCEL" },
        { descripcion: "GALLOPER" },
        { descripcion: "GENESIS" },
        { descripcion: "GRAND I10" },
        { descripcion: "GRAND I10 NIOS" },
        { descripcion: "GRAND SANTA FE" },
        { descripcion: "GRANDEUR" },
        { descripcion: "HB20S" },
        { descripcion: "HB205" },
        { descripcion: "HB20X" },
        { descripcion: "I10" },
        { descripcion: "I20 ACTIVE" },
        { descripcion: "130 CW" },
        { descripcion: "130 WAGON" },
        { descripcion: "130N" },
        { descripcion: "I40" },
        { descripcion: "I40 CW" },
        { descripcion: "IONIQ 5" },
        { descripcion: "IONIQ 6" },
        { descripcion: "IX25" },
        { descripcion: "IX30" },
        { descripcion: "IX35" },
        { descripcion: "IX55" },
        { descripcion: "KONA" },
        { descripcion: "KONA ELECTRIC" },
        { descripcion: "LANTRA" },
        { descripcion: "LAVITA" },
        { descripcion: "MATRIX" },
        { descripcion: "NEXU" },
        { descripcion: "NF SONATA" },
        { descripcion: "NI20" },
        { descripcion: "PONY" },
        { descripcion: "SANTA FE" },
        { descripcion: "SANTA FE CLASSIC" },
        { descripcion: "SANTAMO" },
        { descripcion: "SANTRO" },
        { descripcion: "SCOUPE" },
        { descripcion: "SONATA" },
        { descripcion: "STELAR" },
        { descripcion: "TERRACAN" },
        { descripcion: "TIBURON" },
        { descripcion: "TUCSON" },
        { descripcion: "TUSCANI" },
        { descripcion: "VELOSTER" },
        { descripcion: "VENUE" },
        { descripcion: "VERACRUZ" },
        { descripcion: "VERNA" },
        { descripcion: "XCENT" },
        { descripcion: "XG" },
        { descripcion: "TIGRA" },
        { descripcion: "TORNADO" },
        { descripcion: "TRACKER" },
        { descripcion: "TRAILBLAZER" },
        { descripcion: "TRANS SPORT" },
        { descripcion: "TRAVERSE" },
        { descripcion: "TRAX" },
        { descripcion: "UPLANDER" },
        { descripcion: "VECTRA" },
        { descripcion: "VENTURE" },
        { descripcion: "VIVA" },
        { descripcion: "VOLT" },
        { descripcion: "ÓNIX" },
      ],
    },
    {
      descripcion: "KIA",
      modelos: [
        { descripcion: "RIO" },
        { descripcion: "SPORTAGE" },
        { descripcion: "CEE'D" },
        { descripcion: "CEED" },
        { descripcion: "CERATO" },
        { descripcion: "AVELLA" },
        { descripcion: "CADENZA" },
        { descripcion: "CARES" },
        { descripcion: "CARNIVAL" },
        { descripcion: "CLARUS" },
        { descripcion: "E-NIRO" },
        { descripcion: "ELAN" },
        { descripcion: "ETERPRISE" },
        { descripcion: "EV6" },
        { descripcion: "FORTE" },
        { descripcion: "JOICE" },
        { descripcion: "K5 " },
        { descripcion: "K8" },
        { descripcion: "K900" },
        { descripcion: "MAGETIS" },
        { descripcion: "MOHAVE" },
        { descripcion: "NIRO" },
        { descripcion: "OPIRUS " },
        { descripcion: "OPTIMA " },
        { descripcion: "PICANTO" },
        { descripcion: "POTENTIA" },
        { descripcion: "PRIDE" },
        { descripcion: "PROCEED " },
        { descripcion: "PROCEED GT" },
        { descripcion: "QUORIS" },
        { descripcion: "RETONA" },
        { descripcion: "RIO X" },
        { descripcion: "RIO X-LINE" },
        { descripcion: "SEDONA" },
        { descripcion: "SELTOS" },
        { descripcion: "SEPHIA" },
        { descripcion: "SHUMA " },
        { descripcion: "SONET" },
        { descripcion: "SORENTO" },
        { descripcion: "SOUL" },
        { descripcion: "SPECTRA" },
        { descripcion: "STINGER 3.3" },
        { descripcion: "STINGER GT" },
        { descripcion: "STONIC " },
        { descripcion: "VENGA" },
        { descripcion: "VISTO" },
        { descripcion: "S-TREK" },
        { descripcion: "SCEED" },
      ],
    },
    {
      descripcion: "NISSAN",
      modelos: [
        { descripcion: "QASHQAI" },
        { descripcion: "MICRA" },
        { descripcion: "ALMERA" },
        { descripcion: "JUKE" },
        { descripcion: "X-TRAIL" },
        { descripcion: "100SX" },
        { descripcion: "180SX" },
        { descripcion: "200SX" },
        { descripcion: "240SX" },
        { descripcion: "280SX" },
        { descripcion: "350SX" },
        { descripcion: "350Z" },
        { descripcion: "370 Z" },
        { descripcion: "AD" },
        { descripcion: "ALMERA CLASSIC" },
        { descripcion: "ALMERA G15" },
        { descripcion: "ALMERA TINO" },
        { descripcion: "ALTIMA" },
        { descripcion: "APRIO " },
        { descripcion: "ARIYA" },
        { descripcion: "ARMADA" },
        { descripcion: "AVENIR" },
        { descripcion: "BLUEBIRD" },
        { descripcion: "BLUEBIRD SYLPHY" },
        { descripcion: "CEDRIC " },
        { descripcion: "CEFIRO " },
        { descripcion: "CHERRY" },
        { descripcion: "CIMA" },
        { descripcion: "CREW" },
        { descripcion: "CUBE " },
        { descripcion: "DAYZ" },
        { descripcion: "EVALIA" },
        { descripcion: "EXPERT" },
        { descripcion: "FAIR LADY " },
        { descripcion: "FIGARO" },
        { descripcion: "FRONTIER" },
        { descripcion: "FUGA" },
        { descripcion: "GLORIA" },
        { descripcion: "GRAND LIVINA " },
        { descripcion: "GT-R" },
        { descripcion: "KICKS" },
        { descripcion: "KING-CAB" },
        { descripcion: "CUBISTAR" },
        { descripcion: "LAFESTA" },
        { descripcion: "LATIO" },
        { descripcion: "LAUREL " },
        { descripcion: "LEAF" },
        { descripcion: "LEOPARD" },
        { descripcion: "LIBERTY" },
        { descripcion: "LIVINA GENISS" },
        { descripcion: "LUCINO" },
        { descripcion: "M12" },
        { descripcion: "MAGNITE" },
        { descripcion: "MAXIMA" },
        { descripcion: "MAXIMA QX" },
        { descripcion: "MISTRAL" },
        { descripcion: "MOCO " },
        { descripcion: "MURANO" },
        { descripcion: "NAVARA" },
        { descripcion: "NOTE" },
        { descripcion: "NP300" },
        
        { descripcion: "NV 150AD" },
        { descripcion: "NX" },
        { descripcion: "OTTI" },
        { descripcion: "PATHFINDRE" },
        { descripcion: "PATROL" },
        { descripcion: "PICKUP" },
        { descripcion: "PIXO" },
        { descripcion: "PLATINO " },
        { descripcion: "PRAIRIE" },
        { descripcion: "PRESEA" },
        { descripcion: "PRESIDENT" },
        { descripcion: "PRIMERA" },
        { descripcion: "PULSAR" },
        { descripcion: "QASHQAI+2" },
        { descripcion: "QUEST" },
        { descripcion: "QEQUIS" },
        { descripcion: "R'NESSA" },
        { descripcion: "RASHEEN" },
        { descripcion: "ROGUE " },
        { descripcion: "ROOX" },
        { descripcion: "SAFARI" },
        { descripcion: "SENTRA" },
        { descripcion: "SILVIA" },
        
        { descripcion: "SKYLINE" },
        { descripcion: "STAGEA" },
        { descripcion: "STANZA" },
        { descripcion: "SUNNY" },
        { descripcion: "SYLPY EV" },
        { descripcion: "TEANA" },
        { descripcion: "TERRANO" },
        { descripcion: "TERRANO II" },
        { descripcion: "TIIDA " },
        { descripcion: "TINO" },
        { descripcion: "TITAN" },
        { descripcion: "TRADE 100" },
        { descripcion: "TSURU" },
        
        { descripcion: "V DRIVE" },
        { descripcion: "VERSA" },
        { descripcion: "WINGROAD" },
        { descripcion: "XTERRA" },
      ],
    },
    { descripcion: "HONDA",
    modelos: [
      { descripcion: "ACCORD" },
      { descripcion: "ACCORD EX" },
      { descripcion: "ACCORD EX-R" },
      { descripcion: "CIVIC" },
      { descripcion: "CIVIC EX" },
      { descripcion: "CR-V" },
      { descripcion: "HRV" },
      { descripcion: "LEGEND" },
      { descripcion: "ODISSED" },
      { descripcion: "PILOT" },
      { descripcion: "PILOT TOURING" },
      { descripcion: "RU687GENX KK HR-V" },
      { descripcion: "WR-V" },
    ], }, 
    { descripcion: "FORD",
    modelos: [
      { descripcion: "FIESTA" },
      { descripcion: "ECOSPORT" },
      { descripcion: "KUGA" },
      { descripcion: "MUSTANG" },
      { descripcion: "FOCUS" },
      { descripcion: "TRANSIT" },
      { descripcion: "MONDEO" },
      { descripcion: "FOCUS RS" },
      { descripcion: "RANGER" },
      { descripcion: "TOURNEO" },
      { descripcion: "TRANSIT VAN" },
      { descripcion: "TRANSIT CURIER" },
      { descripcion: "TRANSIT CONNERT" },
      { descripcion: "TRANSIT CUSTOM" },
    ], },
    { descripcion: "BMW",
    modelos: [
      { descripcion: "BMW X7" },
      { descripcion: "BMW X6" },
      { descripcion: "BMW X6 M" },
      { descripcion: "NUEVO BMW X5" },
      { descripcion: "BMW X5 M" },
      { descripcion: "BMW X4" },
      { descripcion: "BMW X4 M" },
      { descripcion: "BMW X3" },
      { descripcion: "BMW X3 XDRIVE30E" },
      { descripcion: "BMW X3 M" },
      { descripcion: "NUEVO BMW X2" },
      { descripcion: "NUEVO BMW X2 M35I" },
      { descripcion: "BMW X1" },
      { descripcion: "BMW M8 COUPE" },
      { descripcion: "BMW SERIES 5 M" },
      { descripcion: "BMW M440I XDRIVE GRAN COUPE" },
      { descripcion: "BMW M4 CONVERTIBLE" },
      { descripcion: "BMW M4 COUPE" },
      { descripcion: "BMW M3 SEDAN" },
      { descripcion: "BMW Z4 M40I" },
      { descripcion: "BMW SERIES 8 COUPE" },
      { descripcion: "BMW M8 COUPE" },
      { descripcion: "BMW SERIES 7 HIBRIDO ENCHUFABLE" },
      { descripcion: "BMW SERIES 5 SEDAN 2020" },
      { descripcion: "BMW M4 COUPE" },
      { descripcion: "BMW SERIE 4 GRAN COUPE" },
    ], },
    { descripcion: "AUDI",
    modelos: [
      { descripcion: "A1" },
      { descripcion: "A3" },
      { descripcion: "A4" },
      { descripcion: "A5" },
      { descripcion: "A6" },
      { descripcion: "A7" },
      { descripcion: "A8" },
      { descripcion: "E-TRON" },
      { descripcion: "E-TRON GT" },
      { descripcion: "E-TRON SPORTBACK" },
      { descripcion: "Q1" },
      { descripcion: "Q2" },
      { descripcion: "Q3" },
      { descripcion: "Q4" },
      { descripcion: "Q4 E-TRON" },
      { descripcion: "Q5" },
      { descripcion: "Q6 E-TRON" },
      { descripcion: "Q7" },
      { descripcion: "Q8" },
      { descripcion: "Q8 E-TRON" },
      { descripcion: "R8" },
      { descripcion: "TT" },
    ], },
    { descripcion: "LAND ROVER",
    modelos: [
      { descripcion: "DEFENDER" },
      { descripcion: "DISCOVERY" },
      { descripcion: "DISCOVERY SPORT" },
      { descripcion: "FREELANDER 2" },
      { descripcion: "RANGE ROVER" },
      { descripcion: "RANGE ROVER EVOQUE" },
      { descripcion: "RANGE ROVER SPORT" },
      { descripcion: "RANGE ROVER VELAR" },
    ], },
    { descripcion: "JEEP",
    modelos: [
      { descripcion: "GRAN CHEROKEE" },
      { descripcion: "WRANGLER" },
      { descripcion: "COMPASS" },
      { descripcion: "CHEROKEE" },
    ], },
    { descripcion: "RENAULT",
    modelos: [
      { descripcion: "ARKANA" },
      { descripcion: "AUSTRAL" },
      { descripcion: "CAPTUR" },
      { descripcion: "CLIO" },
      { descripcion: "ESPACE" },
      { descripcion: "KANGOO" },
      { descripcion: "KOLEOS" },
      { descripcion: "MEGANE" },
      { descripcion: "SPACECLASS" },
      { descripcion: "TRAFIC" },
      { descripcion: "TWINGO" },
      { descripcion: "ZOE" },
    ], },
    { descripcion: "PEUGEOT",
    modelos: [
      { descripcion: "108" },
      { descripcion: "2008" },
      { descripcion: "207" },
      { descripcion: "208" },
      { descripcion: "3008" },
      { descripcion: "308" },
      { descripcion: "4008" },
      { descripcion: "408" },
      { descripcion: "5008" },
      { descripcion: "508" },
      { descripcion: "BRIPPER" },
      { descripcion: "ION" },
      { descripcion: "PARTNER" },
      { descripcion: "RCZ" },
      { descripcion: "RIFTER" },
      { descripcion: "TRAVELLER" },
    ], },
    { descripcion: "SUZUKI",
    modelos: [
      { descripcion: "CELERIO" },
      { descripcion: "NEW VITARA" },
      { descripcion: "IGNIS" },
      { descripcion: "JIMNY" },
      { descripcion: "S-CROSS" },
      { descripcion: "LJ80" },
      { descripcion: "JLX" },
      { descripcion: "FRONTE" },
      { descripcion: "CEMENT" },
      { descripcion: "CERVO" },
      { descripcion: "ST20K/V" },
      { descripcion: "ST30K /V" },
      { descripcion: "ST80K /V" },
      { descripcion: "ST90K /V" },
      { descripcion: "CIAZ" },
      { descripcion: "APV" },
      { descripcion: "ERTIGA" },
      { descripcion: "ERTIGA DREZA" },
      { descripcion: "ALTO" },
      { descripcion: "ALTO JUNA" },
      { descripcion: "EQUATOR" },
      { descripcion: "LAPIN" },
      { descripcion: "BALENO" },
      { descripcion: "ESTEEM (CULTUS)" },
      { descripcion: "SWIFT" },
      { descripcion: "ESCUD" },
      { descripcion: "SANTANA" },
      { descripcion: "SC 100" },
      { descripcion: "FORENZA" },
      { descripcion: "ESCUDO PIKES PEAKS VERSION" },
      { descripcion: "XL7 PIKES PEAKS SPECIAL" },
      { descripcion: "WAGON R+" },
      { descripcion: "PALETTE" },
      { descripcion: "NEW DZIRE" },
    ], },
    { descripcion: "FIAT",
    modelos: [
      { descripcion: "PULSE" },
      { descripcion: "CRONOS" },
      { descripcion: "ARGO" },
      { descripcion: "TORO" },
      { descripcion: "STRADA" },
      { descripcion: "MOBI" },
      { descripcion: "UNO" },
      { descripcion: "500" },
      { descripcion: "500 ABARTH" },
      { descripcion: "500X" },
      { descripcion: "TIPO" },
      { descripcion: "FIORINO" },
      { descripcion: "DOBLO CARGO" },
    ], },
    { descripcion: "CITROEN", 
      modelos: [
      { descripcion: "NUEVO C3" },
      { descripcion: "C4 CACTUS" },
      { descripcion: "C5 AIRCROSS" },
      { descripcion: "BERLINGO MULTISPACE" },
      { descripcion: "BERLINGO FURGÓN" },
      { descripcion: "JUMPER FURGÓN" },
      { descripcion: "JUMPER CHASSIS CABINA" },
      { descripcion: "JUMPY FURGÓN" },
    ],},
    { descripcion: "SKODA", 
      modelos: [
      { descripcion: "NUEVO" },
      { descripcion: "FABIA" },
      { descripcion: "KAMIQ" },
      { descripcion: "SCALA" },
      { descripcion: "KAROQ" },
      { descripcion: "OCTABIA" },
      { descripcion: "OCTABIA COMBI" },
      { descripcion: "SUPERB" },
    ], },
    { descripcion: "VOLVO", 
      modelos: [
      { descripcion: "EX30 2023" },
      { descripcion: "XC40 2022" },
      { descripcion: "EX90 2023" },
      { descripcion: "S60 2021" },
    ], },
    { descripcion: "JAGUAR", 
      modelos: [
      { descripcion: "F‑PACE" },
      { descripcion: "F‑TYPE COUPÉ" },
      { descripcion: "F‑TYPE CONVERTIBLE" },
      { descripcion: "E‑PACE" },
    ], },
    { descripcion: "DODGE", 
      modelos: [
      { descripcion: "400" },
      { descripcion: "600" },
      { descripcion: "1500" },
      { descripcion: "3700" },
      { descripcion: "ARIES" },
      { descripcion: "ASPEN" },
      { descripcion: "ATTITUDE" },
      { descripcion: "AVENGE" },
      { descripcion: "CALIBER" },
      { descripcion: "CARAVAN" },
      { descripcion: "CHALLENGER" },
      { descripcion: "CHARGER" },
      { descripcion: "CHARGER (B-BODY)" },
      { descripcion: "CHARGER (LX)" },
      { descripcion: "CHEROKEE" },
      { descripcion: "COLT" },
      { descripcion: "CORONADO" },
      { descripcion: "CORONET" },
      { descripcion: "D SERIES" },
      { descripcion: "DART" },
      { descripcion: "DART (ESPAÑA)" },
      { descripcion: "DART GT (2012)" },
      { descripcion: "CHARGER DAYTONA" },
      { descripcion: "DAKOTA" },
      { descripcion: "DAYTONA" },
      { descripcion: "DIPLOMAT" },
      { descripcion: "DURANGO" },
      { descripcion: "DYNASTY" },
      { descripcion: "NEON SRT-4" },
      { descripcion: "GTX" },
      { descripcion: "INTREPID" },
      { descripcion: "JOURNEY" },
      { descripcion: "LANCER" },
      { descripcion: "LINEA DODGER (ARGENTINA)" },
      { descripcion: "MAGNUM" },
      { descripcion: "MIRADA" },
      { descripcion: "MONACO" },
      { descripcion: "NITRO" },
      { descripcion: "OMNI" },
      { descripcion: "POLARA" },
      { descripcion: "POLARA (ARGENTINA)" },
      { descripcion: "RAM SRT 10" },
      { descripcion: "RAMCHARGER" },
      { descripcion: "RAM PICKUP" },
      { descripcion: "SPIRIT" },
      { descripcion: "STRATUS" },
      { descripcion: "SUPER BEE" },
    ], },
    { descripcion: "CHRYSLER",
      modelos: [
      { descripcion: "300M" },
      { descripcion: "CIRRUS" },
      { descripcion: "CONCORDE" },
      { descripcion: "NORSEMAN" },
      { descripcion: "SIX" },
      { descripcion: "CROSSFIRE" },
    ], },
    { descripcion: "RAM",
      modelos: [
      { descripcion: "700 SLT" },
      { descripcion: "700 SLT CABINA DOBLE" },
      { descripcion: "700 BIGHORN" },
      { descripcion: "700 LARAMIE" },
    ], },
    { descripcion: "GEELY",
    modelos: [
      { descripcion: "AZKARRA" },
      { descripcion: "COOLRAY" },
    ], },
    { descripcion: "BYD",
    modelos: [
      { descripcion: "HAN EV" },
      { descripcion: "YUAN PLUS" },
      { descripcion: "DOLPHIN EV" },
      { descripcion: "TANG EV" },
    ], },
    { descripcion: "ZOTYE",
    modelos: [
      { descripcion: "2008" },
      { descripcion: "5008" },
      { descripcion: "Cloud 100" },
      { descripcion: "Cloud 100PLUS" },
      { descripcion: "Coupa " },
      { descripcion: "E200 " },
      { descripcion: "M300 " },
      { descripcion: "SESAME " },
      { descripcion: "SR7 " },
      { descripcion: "SR9 " },
      { descripcion: "T200" },
      { descripcion: "T300" },
      { descripcion: "T500" },
      { descripcion: "T600" },
      { descripcion: "T600 COUPLE" },
      { descripcion: "T700" },
      { descripcion: "T800" },
      { descripcion: "V10" },
      { descripcion: "DOMY X5" },
      { descripcion: "DOMY X7" },
      { descripcion: "Z100" },
      { descripcion: "Z200" },
      { descripcion: "Z200HB" },
      { descripcion: "Z300" },
      { descripcion: "Z360" },
      { descripcion: "Z500" },
      { descripcion: "Z500EV" },
      { descripcion: "Z560" },
      { descripcion: "Z700" },
    ], },
    { descripcion: "LIFAN",
    modelos: [
      { descripcion: "SOLANO" },
      { descripcion: "X60" },
      { descripcion: "320 (SMILY)" },
      { descripcion: "BREEZ" },
      { descripcion: "530" },
    ], },
    { descripcion: "JAC",
    modelos: [
      { descripcion: "T8" },
      { descripcion: "T6" },
      { descripcion: "T8 PRO" },
      { descripcion: "S3" },
      { descripcion: "HFC 1037 DKST" },
      { descripcion: "HFC 1035" },
      { descripcion: "JS2" },
      { descripcion: "JS3" },
      { descripcion: "JS4" },
    ], },
    { descripcion: "CHERY",
    modelos: [
      { descripcion: "ARRIZO 5 PRO" },
      { descripcion: "TIGGO 2 PRO" },
      { descripcion: "TIGGO 7" },
      { descripcion: "TIGGO 8" },
      { descripcion: "TIGGO 8 PRO" },
      { descripcion: "TIGGO 8 PRO PHEV" },
      { descripcion: "TIGGO 7 PRO MHEV" },
    ], },
    { descripcion: "HAVAL",
    modelos: [
      { descripcion: "ALL NEW H2 JOLION" },
      { descripcion: "H6 TERCERA GENERACION" },
      { descripcion: "H6 HIBRIDO" },
      { descripcion: "ALL NEW H2 JOLION HIBRIDO" },
    ], },
    { descripcion: "GREAT WALL",
    modelos: [
      { descripcion: "C30" },
      { descripcion: "C30 CONFORT" },
      { descripcion: "C30 FULL LUXURY" },
      { descripcion: "FLORID" },
      { descripcion: "H3" },
      { descripcion: "H3 2.0" },
      { descripcion: "H5" },
      { descripcion: "H5 DIESEL" },
      { descripcion: "H5 ELITE" },
      { descripcion: "H5 FULL" },
      { descripcion: "H5 LUXURY" },
      { descripcion: "H5 SUPER FULL" },
      { descripcion: "H5 TURBO" },
      { descripcion: "H5 TURBO 4X2 AC" },
      { descripcion: "H5 TURBO 4X4 AC" },
      { descripcion: "H6" },
      { descripcion: "H6 COUPE" },
      { descripcion: "HAVAL  H2" },
      { descripcion: "HAVAL H3 4X2" },
      { descripcion: "HAVAL H5" },
      { descripcion: "HAVAL H6" },
      { descripcion: "HAVAL H6 SUPREME" },
      { descripcion: "HAVAL H9" },
      { descripcion: "HAVAL M4" },
      { descripcion: "HOVER" },
      { descripcion: "HOVER H3 FULL" },
      { descripcion: "HOVER H5 ELITE" },
      { descripcion: "HOVER H5 FULL" },
      { descripcion: "M4" },
      { descripcion: "M4 LUXURY" },
      { descripcion: "PEGASUS" },
      { descripcion: "POER" },
      { descripcion: "STEED" },
      { descripcion: "VOLEEX C30" },
      { descripcion: "WINGLE" },
      { descripcion: "WINGLE 3 4X2 CD" },
      { descripcion: "WINGLE 3 4X2 CS" },
      { descripcion: "WINGLE 3 4X4 CS" },
      { descripcion: "WINGLE 4X2 DIESEL CD PICK UP" },
      { descripcion: "WINGLE 4X2 GAS CD PICK UP" },
      { descripcion: "WINGLE 4X2 GAS CS PICK UP" },
      { descripcion: "WINGLE 4X4 DIESEL CD PICK UP" },
      { descripcion: "WINGLE 5" },
      { descripcion: "WINGLE 5 AC CD 4X2" },
      { descripcion: "WINGLE 5 AC CD 4X4" },
      { descripcion: "WINGLE 5 CS CD 4X2" },
      { descripcion: "WINGLE 5 CS CD 4X4" },
      { descripcion: "WINGLE 7 2.0 CD 4X2 DIESEL" },
      { descripcion: "WINGLE 7 2.0 CD 4X4 DIESEL" },
      { descripcion: "WINGLE 7 2.0 CD 4X2 GASOLINA" },
      { descripcion: "WINGLE 7 DIESEL" },
      { descripcion: "WINGLE STEED 2.4 CD 4X2 TM" },
    ], },
    { descripcion: "FOTON",
    modelos: [
      { descripcion: "GRATOUR" },
      { descripcion: "GRATOUR IX" },
      { descripcion: "TOANO" },
      { descripcion: "TUNLAND" },
      { descripcion: "VIEW CS2" },
    ], },
    { descripcion: "DONGFENG",
    modelos: [
      { descripcion: "560" },
      { descripcion: "580" },
      { descripcion: "AX4" },
      { descripcion: "AX7" },
      { descripcion: "CITYVAN" },
      { descripcion: "DFA" },
      { descripcion: "RICH" },
    ], },
    { descripcion: "BRILLIANCE",
    modelos: [
      { descripcion: "SWM G05" },
      { descripcion: "SHINERAY T30" },
      { descripcion: "SHINERAY T32" },
      { descripcion: "SHINERAY T30" },
      { descripcion: "SHINERAY T50" },
      { descripcion: "SHINERAY T52" },
    ], },
    { descripcion: "JMC",
    modelos: [
      { descripcion: "JMC PICKUP " },
      { descripcion: "JMC PICKUP 4×2 " },
      { descripcion: "JMC PICKUP 4×4 " },
      { descripcion: "JMC MINI-BUS" },
      { descripcion: "JMC PANEL VAN" },
      { descripcion: "JMC CAMION" },
    ], },
    { descripcion: "JMC LANDWIND",
    modelos: [
      { descripcion: "CAMION 3.5 TONELADAS" },
      { descripcion: "JX1043DL2TM" },
      { descripcion: "S350" },
      { descripcion: "TIGER 5" },
      { descripcion: "JX 1062 TG 23" },
      { descripcion: "Landwind X2" },
      { descripcion: "VIGUS PLUS" },
      { descripcion: "VIGUS WORK" },
      { descripcion: "VIGUS" },
      { descripcion: "VIGUS PRO" },
    ], },
    // Agrega más marcas y modelos según sea necesario
  ];
  
  async function seed() {
    try {
      const marcas = await MarcaModel.findAll();
      if(marcas && marcas.length <= 0){
      for (const marcaData of marcasData) {
        const { modelos, ...marcaWithoutModelos } = marcaData;
        const existingMarca = await MarcaModel.findOne({
          where: { descripcion: marcaWithoutModelos.descripcion },
        });
        if (!existingMarca) {
          const marca = await MarcaModel.create(marcaWithoutModelos);
          if (Array.isArray(modelos)) {
            for (const modeloData of modelos) {
              const modelo = await ModeloModel.create({
                descripcion: modeloData.descripcion,
                id_marca: marca.id,
              });
            }
          }
        }
      }
    }
    } catch (error) {
      console.error("Error al insertar datos de marcas y modelos:", error);
    } 
  }
  
  MarcaModel.hasMany(ModeloModel, { foreignKey: "id_marca" });
  ModeloModel.belongsTo(MarcaModel, { foreignKey: "id_marca" });
  
  seed();
  
  
  
  